env:
  node: true
  commonjs: true
  es2020: true
  es6: true
  jest/globals: true
extends:
  - "eslint:recommended"
  - "plugin:prettier/recommended"
plugins:
  - prettier
  - jest
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  prettier/prettier:
    - error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
    - { avoidEscape: true }
  semi:
    - error
    - always
  no-undef:
    - warn
  no-dupe-keys:
    - warn
  no-unused-vars:
    - error
    - { argsIgnorePattern: \b(?:res|req|next)\b }
  no-prototype-builtins:
    - off
overrides:
  - files: ["**/*.ts", "**/*.tsx"]
    env:
      node: true
      commonjs: true
      es2020: true
      es6: true
      jest/globals: true
    extends:
      - "eslint:recommended"
      - "plugin:prettier/recommended"
      - "plugin:@typescript-eslint/eslint-recommended"
      - "plugin:@typescript-eslint/recommended"
    plugins:
      - prettier
      - jest
    parser: "@typescript-eslint/parser"
    parserOptions:
      ecmaVersion: 11
    rules:
      prettier/prettier:
        - error
      "@typescript-eslint/ban-types":
        - off
      "@typescript-eslint/explicit-module-boundary-types":
        - off
      "@typescript-eslint/no-explicit-any":
        - off
      linebreak-style:
        - error
        - unix
      quotes:
        - error
        - double
        - { avoidEscape: true }
      semi:
        - error
        - always
      no-prototype-builtins:
        - off
      no-undef:
        - warn
      "@typescript-eslint/no-unused-vars":
        - error
        - { argsIgnorePattern: \b(?:res|req|next)\b }