version: '2.1'
services:
  saml-proxy:
    build:
      context: ../.
      dockerfile: saml-proxy/Dockerfile
    ports:
      - "7000:7000"
      - "9230:9230"
    command: 'node build/app.js --inspect=0.0.0.0:9230 --config dev-config.json'
