version: '2.1'
services:
  saml-proxy:
    build:
      context: ../.
      dockerfile: saml-proxy/Dockerfile
    ports:
      - "7000:7000"
    command: 'node build/app.js --inspect=0.0.0.0:9229 --config dev-config.json'
