version: '2.1'
services:
  redis:
    image: redis
    networks: 
      - 'default'
    ports: 
      - '6379:6379'
    expose:
      - '6379'
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
       - "18081:8081"
    depends_on:
      - redis
  saml-proxy:
    build:
      context: ./
      dockerfile: Dockerfile
      target: deploy
    ports:
      - '7000:7000'
    volumes:
      - ./dev-config.json:/etc/saml-proxy/config.json:Z
    command: "node build/app.js --config /etc/saml-proxy/config.json"
