version: '2.1'
services:
  redis:
    image: redis
    networks: 
      - 'default'
    ports: 
      - '6379:6379'
    expose:
      - '6379'
  saml-proxy:
    build:
      context: ./
      dockerfile: Dockerfile
      target: deploy
    ports:
      - '7000:7000'
    volumes:
      - ./dev-config.json:/etc/saml-proxy/config.json:Z
    command: "node build/app.js --config /etc/saml-proxy/config.json"
