version: '2.1'
services:
  redis:
    image: redis
    networks: 
      - 'default'
    ports: 
      - '6379:6379'
    expose:
      - '6379'
  saml-proxy:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '7000:7000'
      - "9228:9228"
    command: 'node --inspect=0.0.0.0:9228 build/app.js --config dev-config.json'
