version: '2.1'
services:
  redis:
    image: redis
    networks: 
      - 'default'
    ports: 
      - '6379:6379'
    expose:
      - '6379'
  saml-proxy:
    build:
      context: ./
      dockerfile: DockerfileFG
    ports:
      - '7000:7000'
    command: 'node build/app.js --config dev-config.json'
    volumes:
      - ./dev-config.json:/etc/saml-proxy/config.json
    command: "node build/app.js --config /etc/saml-proxy/config.json"
