# This dockerfile is only used during ci/cd to run regression tests following the ci/cd deploy.

FROM ghcr.io/department-of-veterans-affairs/health-apis-docker-octopus/developer-utils:v2 as devchromebase

# Build Args
ARG BUILD_DATE_TIME
ARG BUILD_VERSION
ARG BUILD_NUMBER
ARG BUILD_TOOL

# Static Labels
LABEL org.opencontainers.image.authors="Pivot!" \
      org.opencontainers.image.url="https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/blob/master/Dockerfile.test" \
      org.opencontainers.image.documentation="https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/blob/master/test/regression_tests/README.md" \
      org.opencontainers.image.vendor="lighthouse" \
      org.opencontainers.image.title="lighthouse-saml-tests" \
      org.opencontainers.image.source="https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy" \
      org.opencontainers.image.description="SAML Proxy Tests for Lighthouse APIs"

# Install chrome dependencies
RUN yum -y install https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

FROM devchromebase as devnodebase

# #
# # NodeJS 18.x
# #
# RUN curl -sL https://rpm.nodesource.com/setup_18.x | bash -
# RUN retry yum install -y -q nodejs gcc-c++ make python3 git \
#   && retry yum install --assumeyes --quiet tar gzip xz zip unzip
# RUN npm install -g npm@7.15.1

FROM devnodebase

USER lhuser
WORKDIR /home/lhuser
COPY --chown=lhuser:lhuser ./test/regression_tests/ .
RUN npm i

ENTRYPOINT ["./entrypoint_test.sh"]

# Dynamic Labels
LABEL org.opencontainers.image.created=${BUILD_DATE_TIME} \
      org.opencontainers.image.version=${BUILD_VERSION} \
      gov.va.build.number=${BUILD_NUMBER} \
      gov.va.build.tool=${BUILD_TOOL}
