FROM vasdvp/lighthouse-node-application-base:node12

USER root

COPY --chown=node:node ./test/regression_tests/ .
COPY --chown=node:node ./entrypoint_test.sh ./entrypoint_test.sh

RUN npm i

# Install chrome dependencies
RUN yum install -y -q alsa-lib.x86_64 \
                      atk.x86_64 \
                      cups-libs.x86_64 \
                      gtk3.x86_64 \
                      ipa-gothic-fonts \
                      libXcomposite.x86_64 \
                      libXcursor.x86_64 \
                      libXdamage.x86_64 \
                      libXext.x86_64 \
                      libXi.x86_64 \
                      libXrandr.x86_64 \
                      libXScrnSaver.x86_64 \
                      libXtst.x86_64 \
                      pango.x86_64 \
                      xorg-x11-fonts-100dpi \
                      xorg-x11-fonts-75dpi \
                      xorg-x11-fonts-cyrillic \
                      xorg-x11-fonts-misc \
                      xorg-x11-fonts-Type1 \
                      xorg-x11-utils

USER node

ENTRYPOINT ["./entrypoint_test.sh"]