export const SAMLPRXOY_PATH = "/samlproxy";
export const IDP_PATH = "/idp/saml/sso";
export const IDP_SSO = SAMLPRXOY_PATH + IDP_PATH;
export const IDP_METADATA = "/samlproxy/idp/metadata";
export const IDP_REDIRECT = "/samlproxy//idp/redirect";
export const SP_METADATA_URL = "/samlproxy/sp/metadata";
export const SP_ERROR_URL = "/samlproxy/sp/error";
export const SP_VERIFY = "/samlproxy/sp/verify";
export const SP_FAILURE_TO_PROOF = "/samlproxy/sp/failure-to-proof";
