version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - apt-get -y install awscli
      - echo Logging into ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t dvp/oauth-proxy:$CODEBUILD_RESOLVED_SOURCE_VERSION -f oauth-proxy/DockerfileFG .
      - docker tag dvp/oauth-proxy:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/dvp/oauth-proxy:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - docker images
      - docker run --rm --entrypoint='' -w "/home/node" -i dvp/oauth-proxy:$CODEBUILD_RESOLVED_SOURCE_VERSION npm run test
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/dvp/oauth-proxy:$CODEBUILD_RESOLVED_SOURCE_VERSION
