 ######################################################################
#  SAML Proxy CodeBuild Deploy
#
# ***  Maintenance Request Needed for Production deployments   ***
#
# Maintenance Request Documentation:
#  - https://github.com/department-of-veterans-affairs/lighthouse-maintenance
#  - https://community.max.gov/pages/viewpage.action?pageId=2172170301
#  - https://github.com/department-of-veterans-affairs/lighthouse-devops-support
#
# Tool Links:
#  - CodeBuild - https://docs.aws.amazon.com/codebuild/index.html
#  - CodeBuild Environmental Variables - https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
#  - CodeBuild Source Image - ecs-deployer - https://github.com/department-of-veterans-affairs/lighthouse-codebuild-containers/tree/main/ecs-deployer
#  - AWS CLI 2.0 - https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html
#  - ECS Deploy - https://github.com/fabfuel/ecs-deploy
#
# All Custom scripts are on the CodeBuild Environment container.
# https://github.com/department-of-veterans-affairs/lighthouse-codebuild-containers/tree/main/
#
# Custom Scripts:
#  - slackpost.sh
#
######################################################################
version: 0.2
env:
  shell: bash
  variables:
   # Honor Docker ignore at folder level
    DOCKER_BUILDKIT: 1
    # These are the default deploy environments
    ENVIRONMENTS: "dev staging"
    # These are the deployable environments
    DEPLOYABLE_ENVIRONMENTS: "dev staging sandbox prod"
    # Variables needed for ecs deployment
    AWS_APP_NAME: "ecs-saml-proxy"
    IMAGE: "saml-proxy"
  parameter-store:
    # For pulling docker images
    GHCR_USERNAME: "/dvp/devops/GHCR_USERNAME"
    GHCR_TOKEN: "/dvp/devops/GHCR_TOKEN"
    # SLACK_WEBHOOK should be a webhook that posts to the Slack channel you want notifications to go to
    SLACK_WEBHOOK: "/dvp/devops/codebuild_slack_webhook_lighthouse"
    # Values for regression tests
    CLIENT_ID: "/dvp/common/ecs-saml-proxy/codebuild/client_id"
    DEV_IDP: "/dvp/common/ecs-saml-proxy/codebuild/dev_idp"
    SANDBOX_IDP: "/dvp/common/ecs-saml-proxy/codebuild/sandbox_idp"
    AUTHORIZATION_URL: "/dvp/common/ecs-saml-proxy/codebuild/authorization_url"
    USER_PASSWORD: "/dvp/common/ecs-saml-proxy/codebuild/user_password"
    VALID_USER_EMAIL: "/dvp/common/ecs-saml-proxy/codebuild/valid_user_email"
    ICN_ERROR_USER_EMAIL: "/dvp/common/ecs-saml-proxy/codebuild/icn_error_user_email"
    TIMEOUT: "/dvp/common/ecs-saml-proxy/codebuild/regression_test_timeout"
phases:
  install:
    commands:
      # There is considerable slow down in the provisioning phase when using Amazon provided images.
      # Therefore we use our own Alpine based image. In order to activate the Docker Daemon these lines are needed.
      - /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - printenv
  build:
    commands:
      # Set deploy tag to latest if release, commit hash, or deploy tag is not set.
      - |
        if [[ -n ${DEPLOY_TAG} ]]; then
          echo Deploy Tag set
        elif [[ ${RELEASE} ]]; then
          DEPLOY_TAG=${RELEASE}
        elif [[ ${COMMIT_HASH} ]]; then
          DEPLOY_TAG=${COMMIT_HASH:0:7}
        else
          DEPLOY_TAG=$(git tag --sort=-creatordate | grep fargate-saml-proxy | head -1)
          DEPLOY_TAG=${DEPLOY_TAG#*/}
        fi
      - echo "Deployment target set to ${DEPLOY_TAG}"
      - echo "Verifying ${DEPLOY_TAG} exists..."
      - make check_tag IMAGE=${IMAGE} TAG=${DEPLOY_TAG}
      - |
        for env in ${ENVIRONMENTS}; do
          if  [[ ! ${DEPLOYABLE_ENVIRONMENTS[@]} =~ ${env} ]]; then
            echo "${env} is not deployable!"
            exit 1
          fi
          # Production deploys will require a MR number be set. This MR will not be check for validity but will serve as small safety measure for production deploys and reminder to enforce the process.
          if  [[ (${env} == "prod" || ${env} == "sandbox") && ! ${MR} ]]; then
            echo "${env} deployments need a maintenance request prior to deployment!"
            exit 1
          fi
          echo Deploying to ${env}
          # Set Cluster Name
          CLUSTER="dvp-${env}-${AWS_APP_NAME}-cluster"
          # Set Service Name
          SERVICE="dvp-${env}-${AWS_APP_NAME}-service"
          slackpost.sh -t started "Deploying SAML Proxy to ${env}."
          # Actual deploy of new container.
          ecs deploy --no-deregister \
            ${CLUSTER} \
            ${SERVICE} \
            --tag ${DEPLOY_TAG} \
            --timeout 1200 || exit 1
            slackpost.sh -t success "Deployed SAML Proxy to ${env}."
          if [[ ${env} != prod ]] && [[ ${env} != staging ]]; then
            if [[ ${env} = dev ]]; then
              IDP=${DEV_IDP}
            elif [[ ${env} = sandbox ]]; then
              IDP=${SANDBOX_IDP}
            fi
            echo Logging into ECR
            make login
            echo Logging into GHCR
            echo "${GHCR_TOKEN}" | docker login ghcr.io -u ${GHCR_USERNAME} --password-stdin
            echo Running regression tests.
            make regression \
              TAG=${DEPLOY_TAG} \
              IMAGE=${IMAGE}-tests \
              SAML_PROXY_URL=https://${env}-api.va.gov \
              CLIENT_ID=${CLIENT_ID} \
              IDP=${IDP} \
              AUTHORIZATION_URL=${AUTHORIZATION_URL} \
              USER_PASSWORD=${USER_PASSWORD} \
              VALID_USER_EMAIL=${VALID_USER_EMAIL} \
              ICN_ERROR_USER_EMAIL=${ICN_ERROR_USER_EMAIL}
              TIMEOUT=${TIMEOUT}
            if [[ $? -gt 0 ]]; then
              slackpost.sh -t warning "Some regression tests failed."
            fi
          fi
        done
  post_build:
    commands:
      - |
        if [[ ${CODEBUILD_BUILD_SUCCEEDING} -eq 0 ]]; then
          slackpost.sh -t failure "There was an error with the deployment process of SAML Proxy!"
        fi
