version: '2.1'
services:
  proxy-monitor:
    build: .
    ports:
      - "7200:7200"
    volumes:
      - .:/opt/app
    links:
      - oauth-proxy
      - saml-proxy
    command: "--config dev-config.json"
