######################################################################
#   Oauth Proxy CodeBuild Release
#
#
# Tool Links:
#  - CodeBuild - https://docs.aws.amazon.com/codebuild/index.html
#  - CodeBuild Environmental Variables - https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
#  - CodeBuild Enironment Image - ECS deployer - https://github.com/department-of-veterans-affairs/lighthouse-codebuild-containers/tree/main/ecs-deployer
#  - AWS CLI 2.0 - https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html
#  - Git Hub CLI - https://github.com/cli/cli
#
# All Custom scripts are on the CodeBuild Environment container.
# https://github.com/department-of-veterans-affairs/lighthouse-codebuild-containers/tree/main/
#
# Custom Scripts:
#  - slackpost.sh
#  - increment.sh
#######################################################################
version: 0.2
env:
  shell: bash
  variables:
    DEPLOY: "true"
    REPO: "/repos/duganth-va/vets-saml-proxy"
    IMAGE: "oauth-proxy"
  parameter-store:
    GITHUB_TOKEN: "/github_token"
    # SLACK_WEBHOOK should be a webhook that posts to the Slack channel you want notifications to go to
    SLACK_WEBHOOK: "/slack_web_hook"
phases:
  pre_build:
    commands:
      # gh tool presets
      - gh config set prompt disabled
      - gh config set git_protocol ssh
      - COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      # print env variables to Cloud Watch incase of failure
      - printenv
  build:
    commands:
      - slackpost.sh -t started "started OAuth Proxy release..."
      # check ci status of current commit hash
      - ci_status=$(gh api ${repo}/commits/${commit_hash}/status | jq -r .state)
      - |
        echo "commit status: ${ci_status}"
      - |
        while [[ ${ci_status} == "pending" ]]; do
          echo "ci still running -- sleep"
          ci_status=$(gh api ${repo}/commits/${commit_hash}/status | jq -r .state)
          echo "commit status: ${ci_status}"
          sleep 10
        done
      - |
        if [[ ${ci_status} != "success" ]]; then
          echo "ci failed release aborted. ci status was ${ci_status}"
          exit 1
        fi
      # create new tag
      - old_tag=$(git tag --sort=-creatordate | grep fargate-oauth-proxy | head -1)
      - echo "found ${old_tag} - incrementing..."
      # create new tag
      - new_tag=$(increment.sh ${old_tag})
      - echo "creating ${new_tag} release"
      # create release
      - gh release create ${new_tag}
      - echo tag image
      # tag ecr image with release
      - make tag tag=${commit_hash:0:7} new_tag=${new_tag}
      - |
        if [[ ${deploy} == "true" ]]; then
          echo "initiating deploy for ${new_tag}"
          aws codebuild start-build --project-name oauth-proxy-deploy --environment-variables-override name=release,value=${new_tag}
        fi
  post_build:
    commands:
      # post to slack.
      - |
        if [[ ${codebuild_build_succeeding} -eq 0 ]]; then
          slackpost.sh -t failure "there was an error with the release process for ${codebuild_build_id}."
        else
          slackpost.sh -t success "api gateway release ${new_tag} was successful."
        fi
