# name: Weekly Release Build

# on:
#   push:
#     branches: [API-37625-gh-release-build]
#   schedule:
#     - cron: '0 22 * * 1'

# jobs:
#   release_build:
#     runs-on: ubuntu-latest
#     env:
#       REPO: "lighthouse-saml-proxy"
#       IMAGE: "saml-proxy"
#       XCHECKS: "saml-proxy-release"
#     strategy:
#       matrix:
#         environment: ['dev', 'staging']
    
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2
      
#         -name: Setup No
